# Generated by Django 3.0 on 2020-12-18 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('place', models.CharField(choices=[('kp', 'کیانپارس'), ('ka', 'کیان اباد'), ('ks', 'کیانشهر')], default='kp', max_length=2, verbose_name='منطقه')),
                ('phone_number', models.CharField(max_length=12, verbose_name='شماره تلفن')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه ها',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_user', to='core.Group', verbose_name='گروه'),
        ),
    ]
