# Generated by Django 3.0 on 2020-12-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201218_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Group', verbose_name='سازنده'),
        ),
    ]
