# Generated by Django 3.0 on 2020-12-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creator',
            field=models.BooleanField(default=False, verbose_name='سازنده'),
        ),
    ]
