# Generated by Django 3.0 on 2020-12-30 10:26

import core.models.AdvertModels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_advert_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='poster',
            field=models.ImageField(default='image_default\\default.jpg', upload_to=core.models.AdvertModels.change_file_name, verbose_name='پستر'),
        ),
    ]
