# Generated by Django 3.0 on 2021-01-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_advert_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
