# Generated by Django 3.0 on 2021-01-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210101_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='is_private',
        ),
    ]
