# Generated by Django 3.0 on 2021-01-14 16:01

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_advert_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='new_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
