# Generated by Django 3.0 on 2021-01-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_advert_new_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='new_date',
        ),
    ]
